spring:
  application:
    name: taco-order-service
  devtools:
    add-properties: false
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      username: ${DB_USR:root}
      password: ${DB_PASSWD:secret}
      database: ${DB_NAME:TacoDB}
      auto-index-creation: true
server:
  port: ${APP_PORT:9010}

management:
  endpoints:
    web:
      exposure:
        include: env, health, heapdump, info, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}